# manual-refresh: 2026-03-25T01:47:09Z (manual workflow_dispatch)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-npm-dependencies:
        patterns:
          - "*"
