# manual-refresh: initial
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-npm-dependencies:
        patterns:
          - "*"
